### PR TITLE
tab texts to language file

### PR DESCRIPTION
**Pull request by BrockleyJohn**
remove hard-coding of non-paypal tabs on admin / orders

### CODE REVIEW

**Comment by BrockleyJohn** [comment]
added fixes for three known problems with PP app:
- undefined constant error on initial setup (Start)
- UK v GB mismatch between app and osc country table
- force curl to TLSv1.2 instead of SSL (the default on some versions)

**Comment by gburton** [comment]
TY

**Comment by BrockleyJohn** [comment]
done

**Comment by gburton** [comment]
TY

**Comment by gburton** [comment]
Could you send your changes to paypalApp branch please.
You've managed to send to a very old branch of similar name.  My fault for not deleting the branch.
TY

**Pull request merged**
