### PR TITLE
Update Bootstrap to v3.3.6

### PR DESCRIPTION
**Pull request by gburton**

### CODE REVIEW

**Comment by crazy-colorado** [comment]
I'll get this on my dev site today and see if I come across any issues.

Release notes
http://blog.getbootstrap.com/2015/11/24/bootstrap-3-3-6-released/

List of changes
https://github.com/twbs/bootstrap/releases/tag/v3.3.6

**Comment by crazy-colorado** [comment]
So far everything seems to be in order.

**Comment by skleiner** [comment]
Preliminary testing OK so far here.  Only a brief couple minute test process clicking around the shop to see what occurs.

**Comment by gburton** [comment]
Thanks Chaps.  

Agreed, I have spent a couple of hours today testing and fiddling and can find no error..

**Comment by skleiner** [comment]
Couple days gone by in a live shop and all seems OK.  Thanks for keeping edge going.

**Pull request merged**
