### PR TITLE
Hooks Implementation

### PR DESCRIPTION
**Pull request by gburton**

### CODE REVIEW

**Comment by gburton** [comment]
Discussion welcome.  Testing welcome.

**Comment by gburton** [comment]
Next up after this will be adding of the Paypal App.

**Comment by skleiner** [comment]
My includes/application_top.php is not up to date with the most recent Edge but I don't think it matters because I already had the code for hooks integrated there from some earlier work.  So I just updated all the "hooks" files with the commit files. The existing hooks I have are functioning normally.  On the admin side, the hooks box is displaying correctly.

**Comment by BrockleyJohn** [comment]
Tested on clean install. Empty hooks admin page shows as expected. Catalog side works fine (without any hook modules!)

What about admin hooks?

**Comment by gburton** [comment]
> Hooks class constructor is php4 - update to __construct

Done, please test - thanks



> What about admin hooks?

Do any exist?

**Comment by BrockleyJohn** [comment]
Paypal app uses one on admin/orders

**Comment by gburton** [comment]
> Paypal app uses one on admin/orders

Paypal App is not yet core...

**Comment by BrockleyJohn** [comment]
neither are any hooks :) - I just thought if you're going to put it into app top on the shop side, and if paypal app is next up, it might be clearer to put both includes in at the same time.

Unless I'm missing something, there aren't any listeners anyway...

**Comment by gburton** [comment]
All Hooks load from the shop side...

**Comment by BrockleyJohn** [comment]
I guess you mean more than that they live under cat/includes not admin... I'll have to wait to see one

**Comment by gburton** [comment]
> I guess you mean more than that they live under cat/includes not admin... I'll have to wait to see one

All hooks live in the shop side (even the admin side hooks).  Have a look at the Paypal App Hooks.

**Comment by BrockleyJohn** [comment]
> All hooks live in the shop side (even the admin side hooks).
I guessed wrong then! 
> Have a look at the Paypal App Hooks.
I have been - but have only seen the one on admin/orders. Couldn't find any shop-side examples. Am I looking in the wrong places?

**Comment by gburton** [comment]
paypal_app (from addons) > unzip.
look in /includes/hooks/

**Comment by BrockleyJohn** [comment]
contents is
/admin/orders/paypal.php

**Comment by gburton** [comment]
Yes...
Which suggests what ;)

**Comment by BrockleyJohn** [comment]
That we're not participating in the same conversation? 

Surely that's the hook on admin/orders not a shop-side example...

**Comment by gburton** [comment]
/includes/hooks/admin/orders/paypal.php

That is an ADMIN hook, which lives in the include/hooks/ directory SHOPSIDE.

**Comment by BrockleyJohn** [comment]
Yes, I knew that before the first time you said it :) It's the only hook I've ever seen.

I meant an example of a hook that works on the shop side!

**Comment by gburton** [comment]
LOL,ok,  There are examples at the osc forum.

**Pull request merged**
