### PR TITLE
SEO: Category Title

### PR DESCRIPTION
**Pull request by gburton**
Admin Side, Shop Side, Installer

To update existing shop:
ALTER TABLE categories_description ADD categories_seo_title VARCHAR(128) NULL ;

### CODE REVIEW

**Comment by skleiner** [comment]
Once I get the product title caught up I'll move on to this.

**Comment by gburton** [comment]
No worries Steve.  There is no hurry at all.

**Comment by skleiner** [comment]
Updated to 324..all's good on admin side and in shop side breadcrumbs working as expected (options enabled) and meta as expected.

**Comment by gburton** [comment]
@skleiner thank you Steve

**Pull request merged**
