### PR TITLE
Custom Data Attributes

### PR DESCRIPTION
**Pull request by gburton**
Introduces a few HTML5 Data Points.

### CODE REVIEW

**Comment by gburton** [comment]
Would someone please make the changes and report back any problems...or success...
Thanks

**Comment by BrockleyJohn** [comment]
I've put it into a test store which behaves just as before. Manual inspection shows the attributes populated for products with & without attributes, in and out of stock.

**Comment by gburton** [comment]
Thank you @BrockleyJohn - could you message me your URL so that I can take a look?

**Comment by BrockleyJohn** [comment]
done on the forum - can't figure it on here!

**Comment by gburton** [comment]
TY @BrockleyJohn appreciated!

**Pull request merged**
