### PR TITLE
Allow navbar to stay fixed on page

### PR DESCRIPTION
**Pull request by Piernas**
Small addition to allow navbar to stay on screen when scrolling the
content of a page.

### CODE REVIEW

**Comment by BrockleyJohn** [comment]
Perhaps it would be better to reverse the logic so that if added to an existing store without uninstalling and reinstalling, the previous behaviour doesn't change
`$navbar_fixed   = (MODULE_CONTENT_NAVBAR_FIXED == 'Yes') ? ' navbar-fixed-top' : '';  `

**Comment by gburton** [comment]
Thanks

Installer (SQL) change.
CSS change.

Please solve these and push.

**Comment by gburton** [comment]
Please rework the submission so that shopowner can choose "top", "bottom", "default".  
SQL Installer needs updating
CSS needs updating

**Comment by Piernas** [comment]
Done!

**Comment by gburton** [comment]
Thank you.

**Comment by skleiner** [comment]
@gburton @Piernas 
Preliminary Testing via Uniserver in development mode on Chrome, Firefox and Edge.  And Smartphone. All appears to be working OK

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/pull/347

Optimises the code a little bit..

**Comment by rubberfashion** [comment]
Hi,

For mode: on top 

Example: create_account.php on mobile device

When you miss selecting radio button M / F and click on Continue

you will not see the option button M / F, because it is hide by the navbar. You have to scoll up so see it.

Better would be to implement a offset of the high of the navbar. But i do not know how to do.

Also in the Destop mode same issue

By the way ... is it possbile to implement a logo in the navbar? It doesn't look really nice.

Thank you :)

Mobile
screenshot_20170812-130939

Desktop
unbenannt

**Pull request closed without merging**
