### PR TITLE
Remove Grid/List buttons

### PR DESCRIPTION
**Pull request by gburton**
Remove Grid List Buttons if page is not in the allowed page list.

### CODE REVIEW

**Comment by BrockleyJohn** [comment]
Fails testing on first entry in variable eg. advanced_search_result.php

I think the test should be !=== false

**Comment by gburton** [comment]
@BrockleyJohn changed, could you retest please ?

**Comment by BrockleyJohn** [comment]
Now performs as expected

**Comment by gburton** [comment]
@BrockleyJohn thank you for testing, Eddy too.

**Pull request merged**
