### PR TITLE
hook register in application_top.php

### PR DESCRIPTION
**Pull request by raiwa**
auto register hooks

### CODE REVIEW

**Comment by BrockleyJohn** [comment]
Doesn't it also need the register taking out of orders.php? Or does registering twice not matter?

**Comment by raiwa** [comment]
@BrockleyJohn you are right, forgot it to add to Git, thanks

**Comment by gburton** [comment]
Is this 100% tested, and confirmed working with zero problems?

**Comment by gburton** [comment]
I think it's cleaner using basename as filenames could potentially have a . in them.  UNlikely, but could.
Thanks

**Comment by gburton** [comment]
Oh, please push to modularity2 branch.  
Master branch is static now.

**Comment by raiwa** [comment]
Yes, replaced with basename.

Tests conditions:

- latest 2.3.4 BS EDGE under PHP 7.2
- error reporting set to "all"

Tests performed:

- admin side: orders.php, removed hooks register, edited several orders all ok, no errors
- shop side: points and rewards add-on installed, removed all hook registers in several files (checkout_payment, confirmation, process, create account)
- several checkouts completed with points and rewards actions, get points, redeem points, create account. no errors, all redeem points actions correct

**Comment by gburton** [comment]
Pulled into m2 branch, thank you @raiwa for the code and the push to m2.

**Pull request closed without merging**
