### PR TITLE
SEO - Manufacturers

### PR DESCRIPTION
**Pull request by gburton**
Adds Metas and Description.

### CODE REVIEW

**Comment by gburton** [comment]
To test on an existing setup, here is the needed SQL:

ALTER TABLE manufacturersn ADD manufacturers_seo_title VARCHAR( 128 ) NULL;

ALTER TABLE manufacturers_info ADD manufacturers_description TEXT NULL, ADD manufacturers_seo_description TEXT NULL, ADD manufacturers_seo_keywords VARCHAR( 128 ) NULL;

**Comment by skleiner** [comment]
Is using <br /> vs <br> a big deal in an html doctype? I see both are being used in this commit.  The <br> in the manufacturer.php file for one.

**Comment by skleiner** [comment]
code removed above
br /   vs br is what I meant

**Comment by gburton** [comment]
HTML5 says that it can be plain old br or br /

br is a void element, and void elements can optionally be closed with />

So, either is fine.  We should probably standardise one way or the other, but it doesn't really matter.

What do you think ?

**Comment by skleiner** [comment]
If there's a trend in html markup going one way or the other. I'd say use that.  Meaning in a couple years br or br / may be being phased out....or not.
If not, and it doesn't matter go with the one that needs changed the least.
Another note, as the need for the file defines is being phased out do you plan to update that file or just wait until it's totally obsolete.
Domestic duty calls, so it'll be a couple days before I can install this on my live shop.  When I do I'll let you know how it's going. 
thanks

**Pull request closed without merging**
