### PR TITLE
Modular index

### PR DESCRIPTION
**Pull request by gburton**
Ready for primetime?  This is only the front-page of index.php

I'd like to get this into Core (even though index.php is now a mix of modular and "old skool", as it'll take some time to update the other pages (categories, manufacturers).   Anyone for or against?  If against, for what reason(s)...

### CODE REVIEW

**Comment by skleiner** [comment]
I'm good with proceeding. Perhaps a wiki page on this aspect of the project, noting the level affected, so there's no confusion (like I was) to the user.  When the other levels are integrated then the wiki updated?

**Comment by azpro-git** [comment]
> Ready for primetime? This is only the front-page of index.php
> 
> I'd like to get this into Core (even though index.php is now a mix of modular and "old skool", as it'll take some time to update the other pages (categories, manufacturers). Anyone for or against? If against, for what reason(s)...


Definitely a go!

**Comment by flyerart2B** [comment]
Hey there... have we given up on resolving php7 problems? The new modularity is great but oscommerce responsive still does not work on php7 which would seem a priority. Sorry, I had a serious car accident and have been out of the loop so maybe I missed something.

**Comment by gburton** [comment]
@flyerart2B https://github.com/gburton/Responsive-osCommerce/issues/288
Join in the discussion there.

**Comment by azpro-git** [comment]
@gburton Looking at Installer it reminds me of a (critical / potential ?) issue for the setup/installing of modules.
With the modularity we heavily rely on configuration setting MODULE_CONTENT_INSTALLED. If not all settings / permissions are set correctly by shopowner or Installer (possible with different Server settings) the reading of Installed modules can be faulty. Now on line 87 in admin/modules_content.php it reads:
```
if ( implode(';', $_installed) != MODULE_CONTENT_INSTALLED ) {
    tep_db_query("update " . TABLE_CONFIGURATION . " set configuration_value = '" . implode(';', $_installed) . "' where configuration_key = 'MODULE_CONTENT_INSTALLED'");
  }
```
So if $_installed is empty ... MODULE_CONTENT_INSTALLED will be set to empty .. which leaves us with an not working store.

I highly recommend to add   if ( !empty($_installed) ) {  before Line 87.

This off course is also applicable for modules.php

I did some months ago a lot of testing for this issue and cannot remember exactly in which cases $_installed can be empty - But I did learn (the hard way) it can happen!
I also added some $messageStack->add() messages to know / see what is happening in LINE 88 (is MODULE_CONTENT_INSTALLED updated or not) but that is probably just me being overcautious.

As you probably know - I am sorry I don't know how to make a Pull-request. Learning Github is now to much while setting up the new BS store. Still hop this helps!

**Comment by gburton** [comment]
Thanks to all who took the time the test and to post relevant comments.

**Pull request merged**
