### PR TITLE
Pass security check on ext out of the box

### PR DESCRIPTION
**Pull request by BrockleyJohn**
Yes, I know, it's a core change.

But I have to concede that failing one of the security checks out of the box when it's so fixable is pants.

Is there a good reason not to do this?

Tested on existing store and new install

### CODE REVIEW

**Comment by gburton** [comment]
I believe this was left down to the Shopowner...as different servers need different code.  
Have you tested it across a range of servers?

**Comment by BrockleyJohn** [comment]
Fair question - I expect it will only solve for apache (which is all I have tried, although various setups) and otherwise be ignored.. The osc distro does contain other htaccess files so it wouldn't be inconsistent to have this too. I will have a go and see what happens elsewhere and can have a look into a multi-platform approach if you think it worthwhile.

**Comment by gburton** [comment]
You're correct - it would not be inconsistent to have it.

**Comment by gburton** [comment]
TY

**Pull request merged**
