### PR TITLE
Update Breadcrumb to Schema

### PR DESCRIPTION
**Pull request by gburton**
Data Vocabulary to Schema.

### CODE REVIEW

**Comment by skleiner** [comment]
Page Source before update:

<div class="col-sm-12 hidden-xs breadcrumbs">
  <ol class="breadcrumb"><li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="http://www.barkavenuedogboutique.com" itemprop="url"><span itemprop="title"><i class="glyphicon glyphicon-home"><span class="sr-only">Home</span></i></span></a></li>
<li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="http://www.barkavenuedogboutique.com/accessories-for-your-dog-c-115.html" itemprop="url"><span itemprop="title">Accessories For Your Dog</span></a></li>
<li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="http://www.barkavenuedogboutique.com/barrettes-c-115_170.html" itemprop="url"><span itemprop="title">Barrettes</span></a></li>
<li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="http://www.barkavenuedogboutique.com/butterfly-theme-dog-barrette-set-p-479.html" itemprop="url"><span itemprop="title">Butterfly Theme Dog Barrette Set</span></a></li>
</ol></div>

After update:

<div class="col-sm-12 hidden-xs breadcrumbs">
  <ol  itemscope itemtype="http://schema.org/BreadcrumbList" class="breadcrumb"><li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a href="http://www.barkavenuedogboutique.com" itemprop="item"><span itemprop="name"><i class="glyphicon glyphicon-home"><span class="sr-only">Home</span></i></span></a><meta itemprop="position" content="1" /></li>
<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a href="http://www.barkavenuedogboutique.com/accessories-for-your-dog-c-115.html" itemprop="item"><span itemprop="name">Accessories For Your Dog</span></a><meta itemprop="position" content="2" /></li>
<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a href="http://www.barkavenuedogboutique.com/barrettes-c-115_170.html" itemprop="item"><span itemprop="name">Barrettes</span></a><meta itemprop="position" content="3" /></li>
<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a href="http://www.barkavenuedogboutique.com/butterfly-theme-dog-barrette-set-p-479.html" itemprop="item"><span itemprop="name">Butterfly Theme Dog Barrette Set</span></a><meta itemprop="position" content="4" /></li>
</ol></div>

**Comment by skleiner** [comment]
That was supposed to be just the page source but it was converted obviously.

**Comment by gburton** [comment]
@skleiner https://developers.google.com/structured-data/testing-tool?url=http%253A%252F%252Fwww.barkavenuedogboutique.com%252Fbutterfly-theme-dog-barrette-set-p-479.html will show the new style breadcrumb active on site, and all looking good.

**Comment by crazy-colorado** [comment]
Looks good.  Now is read as a breadcrumblist and no longer just breadcrumb.

**Comment by skleiner** [comment]
Got it and thank you.

**Comment by gburton** [comment]
Thank you for testing.

**Pull request merged**
