### PR TITLE
Raiwa undefined constant

### PR DESCRIPTION
**Pull request by raiwa**
If the Header Tag module "Grid List Javascript (jQuery)" is not installed, a undfined constant error is produced in includes/modules/product_listing.php for: MODULE_HEADER_TAGS_GRID_LIST_VIEW_STATUS.

### CODE REVIEW

**Comment by gburton** [comment]
Thank You

**Comment by skleiner** [comment]
@raiwa I was trying to generate the error message in Uniform Server (development mode on) and can't seem to.  Using php 5.5 if I recall correctly.  
Grid List Javascript (jQuery)" is not installed...viewing specials and index but no error. 
I'll try again tomorrow

**Comment by raiwa** [comment]
Hello Steve @skleiner,

The undefined constant and variable errors do not show under php 5.5 and before. At least I do not know how to show them there neither.
You need the following conditions to be fulfilled to show it:
- php 5.6 or 7.0
- error_reporting(E_ALL);
- Grid List Javascript (jQuery) not installed

Thanks for testing
rgds
Rainer

**Comment by BrockleyJohn** [comment]
If you want to see a lot of these messages, change the error reporting setting in admin application_top and then go to install any of the older modules in admin.

If I remember the details properly, the constructor of every uninstalled shipping and order total module throws it when it checks to see if it's enabled.

**Comment by skleiner** [comment]
@raiwa Still no luck with display of that error using Uniform Server.  Trying php 5.6...no errors show. php7 errors show but not undefined constant for example when viewing new products.

Grid List Javascript (jQuery) not installed
Error reporting: 
// set the level of error reporting
  error_reporting(E_ALL & ~E_NOTICE);

Something uniform server related? I don't know.  I cannot test on my live shop either as the host runs php 5.5

**Comment by raiwa** [comment]
Steve,
set Error reporting to:
error_reporting(E_ALL);

**Comment by BrockleyJohn** [comment]
... in [catalog]/includes/application_top.php

**Comment by skleiner** [comment]
@raiwa  Thank you for the clarification.

  I changed that and now in 5.6 for http://localhost/Responsive-osCommerce-master/products_new.php

I see this error:

> Notice: Use of undefined constant MODULE_HEADER_TAGS_GRID_LIST_VIEW_STATUS - assumed 'MODULE_HEADER_TAGS_GRID_LIST_VIEW_STATUS' in C:\Users\Public\Documents\UniServerZ\www\Responsive-osCommerce-master\includes\modules\product_listing.php on line 97

Making the proposed change, the error disappears.

Reverting the the original code, the error reappears. 

Reinstalling the module, the error disappears of course.

I'd say confirmed issue and the fix appears to take care of that.

Thanks

**Comment by raiwa** [comment]
thank you

**Comment by gburton** [comment]
Thank you @raiwa 
Thank you @skleiner & @BrockleyJohn for testing

**Pull request merged**
