### PR TITLE
fix wrong default link in canonical ht

### PR DESCRIPTION
**Pull request by raiwa**
see this messages:
https://forums.oscommerce.com/topic/412885-new-edge-install-unable-to-determine-connection-method-on-a-link/

### CODE REVIEW

**Comment by gburton** [comment]
Link should be NONSSL. TY for PR, please remove https://github.com/gburton/Responsive-osCommerce/pull/662/commits/48bfc816250c1707a4dfe5e15022fd6f04b0276b so I can pull.

**Comment by raiwa** [comment]
Are you sure?
I found this resource:
[https://searchengineland.com/https-setup-causing-seo-issues-254236](url)
It says:
Ensure canonical tags point to the HTTPS URL versions.

And this:
[https://moz.com/community/q/can-i-leave-off-http-https-in-a-canonical-tag](url)
Google prefers HTTPS pages over equivalent HTTP pages as canonical, ...

**Comment by boelle** [comment]
@raiwa 

i get this on several pages:

Error!

Unable to determine connection method on a link!

Known methods: NONSSL SSL

will try your change but it might save me

**Comment by gburton** [comment]
> Are you sure?

Yes.

**Pull request closed without merging**
