### PR TITLE
PHP7 compatibility changes - class constructors and evaluation order

### PR DESCRIPTION
**Pull request by BrockleyJohn**
A rebuild of the same set of changes against the latest master.

Please test again - especially moneybookers payment module, which won't install without an account so I haven't been able to.

### CODE REVIEW

**Comment by BrockleyJohn** [comment]
More on testing:

I think the biggest bit for proper testing is the payment modules, so I'd like particularly to ask for help from everyone to check the modules that they use all the way through a payment to an order ready for processing. The same applies for any core shipping modules.

 

The changes that were required to clear deprecated notices were tested quite extensively last year, but some things less so:

- paypal app (was introduced since) could do with a good thrashing

- moneybookers payment module can't be installed without an account (and they refused to give me one)

- most payment modules for specific merchant accounts were checked that they install are selectable as a choice of payment. I only tested paypal standard and cod all the way through a payment and back again. If you have access to a merchant account for one of the others (especially one with callback code in /ext), please take a payment all the way through to complete the lifecycle

- usps shipping module & associated email class (I couldn't get them to work & gave up when @kymation gave me the excuse that they've not worked for ages)

**Comment by BrockleyJohn** [comment]
Worldpay hosted payments tested (and an unrelated bug found!)

**Comment by frankludriks** [comment]
How to download this branch? Excuse my ignorance.

**Comment by BrockleyJohn** [comment]
@frankludriks Go to the branch [https://github.com/BrockleyJohn/Responsive-osCommerce/tree/php_compatibility_02](https://github.com/BrockleyJohn/Responsive-osCommerce/tree/php_compatibility_02) and click the Clone or download button on the right

**Comment by mcmannehan** [comment]
@BrockleyJohn 
This branch https://github.com/BrockleyJohn/Responsive-osCommerce/tree/php_compatibility_02 can't by downloaded by GIT to my server. I get all the time the master branch. How i can do it with Git?
@frankludriks btw: welcome!!!

**Comment by mcmannehan** [comment]
okay now i download the ZIP file. My server runs with PHP7.1.2 and MySQL5.7 the new sql_mode.
I get the first SQL error. I will document and change very unsuitable SQL query error.

**Comment by mcmannehan** [comment]
I recommand for users who runs **NGINX webserver as proxy for Apache** add this to the /admin/.htaccess
**#only activate if your provider use NGINX as proxy for apache**
<IfModule mod_rewrite.c>
 RewriteEngine on
 RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>
Than the Admin HTTP Authentication will work fine.
NGINX don't know the $_SERVER['PHP_AUTH_USER'] and $_SERVER['PHP_AUTH_PW']

**Comment by mcmannehan** [comment]
@BrockleyJohn BrockleyJohn
I did tested in Sandbox all Paypal modules with the PayPal App v5.018 in this version https://github.com/BrockleyJohn/Responsive-osCommerce/tree/php_compatibility_02 i cant find any issue. Everything works fine.

Alle the shipping modules (exclude UPS, i can't test this) working fine too.

**Comment by BrockleyJohn** [comment]
@mcmannehan thanks Manfred - I've only done about an hour's testing on MySQL5.7 (previously it was running against 5.6) so it's good to have that confirmation

**Comment by mcmannehan** [comment]
@BrockleyJohn
You welcome. I did fixed some sql query (MySQL5.7 suitable) in the front end. How i can send you that?

**Comment by BrockleyJohn** [comment]
@mcmannehan  If I understand correctly, you are just working with local copies taken straight from github, so I think the easiest way is for you to email me the changed files. I'll message you on the forums with the email address.

**Comment by mcmannehan** [comment]
@BrockleyJohn 
yes i work with the files from https://github.com/BrockleyJohn/Responsive-osCommerce/tree/php_compatibility_02

i did send you an e-mail already. Enjoy.

**Comment by gburton** [comment]
@skleiner thank you for testing, it is appreciated.
@BrockleyJohn  if you can sort out those two conflicts which I've introduced...I'll pull this in today.

**Comment by BrockleyJohn** [comment]
@gburton there you go!

**Comment by gburton** [comment]
Boom. 
Thank you to all!

**Pull request merged**
