### PR TITLE
Fix Safari problems with flex (grid) layout. 

### PR DESCRIPTION
**Pull request by BrockleyJohn**
Fix for issue #535 
Blank column down right hand side on all versions of Safari due to before/after pseudo-element handling. 
Some older versions (notably on iPad Air) not wrapping or not equalising height, so added backwards compatibility (webkit styles).

### CODE REVIEW

**Comment by BrockleyJohn** [comment]
Think I had a caching issue in the iPad Air 2 emulation and testing was affected by previous content of user.css
iPad Air 2 and Galaxy Tab S2 seem to require webkit flex styles in a separate rule.

**Comment by gburton** [comment]
Is this a fix for Safari where Safari have not got things correct?
In other words, should Safari be making relevant changes?

**Comment by BrockleyJohn** [comment]
I see where you're coming from. There are actually two problem here: 
- one in which Safari gives an empty column down the right hand side in, I think, all versions. This is due to Safari treating the before and after pseudo elements differently than other browsers do but how they should be treated isn't standardised. This could perhaps be seen as a Safari bug but the "fix" is simply to style the before and after elements to make sure they come out how we want, which might be a good thing if the default behaviour of browsers were to change in the future.
- the other problem where some browser versions don't wrap the elements but stick them in a long column. This was initially reported on Safari but then Carine had the same on Chrome. Putting in the older webkit rules makes the styles work on all browsers that support that earlier version of flex.

**Comment by gburton** [comment]
What's the very latest URL for testing?

**Comment by BrockleyJohn** [comment]
Code is the same on both, data maybe better on 
[http://bromleybr.co.uk/bsdev/](http://bromleybr.co.uk/bsdev/)

**Comment by gburton** [comment]
that breaks quite badly in Win10 Chrome...can't work out how to add an image here, so I popped it onto the BS thread at the forum...

**Comment by BrockleyJohn** [comment]
[http://bromleybr.co.uk/reflex/](http://bromleybr.co.uk/reflex/)

Are you looking for any particular behavioural change?

**Comment by gburton** [comment]
@BrockleyJohn  there should be no behavioural change at all.

A mistake was made by us in the early days where we used list-group for the product listing grid/list thing.  this has caused an incompatibility with http://getbootstrap.com/components/#list-group

Changing out .css to .row.list-group solves it.  Makes sense?

**Comment by gburton** [comment]
TY

**Pull request merged**
