### PR TITLE
Font Awesome v5

### PR DESCRIPTION
**Pull request by gburton**
These commits replace FA v4 with FA v5.

### CODE REVIEW

**Comment by gburton** [comment]
The language change needs testing to ensure that Scheme/Microdata (breadcrumb) does not error out...

**Comment by Moxamint** [comment]
1) Isn't 'far' pro version only?
2) Would you consider adding fa-v4-shim.js for v4 compatibility?

**Comment by gburton** [comment]
> Would you consider adding fa-v4-shim.js for v4 compatibility?

We only use a few icons (that need changing), so to perform a global search/replace takes just a few minutes...will list them on a post at forum.

**Comment by gburton** [comment]
https://forums.oscommerce.com/topic/412589-font-awesome-v5/

**Pull request merged**
