### PR TITLE
Datepicker update to Bootstrap Datepicker "format"

### PR DESCRIPTION
**Pull request by raiwa**
Date Format customization  in:
english.php
`define('JQUERY_DATEPICKER_FORMAT', 'mm/dd/yy'); // see http://docs.jquery.com/UI/Datepicker/formatDate`
won't work anymore.
.Jquery Datepicker "formatDate" needs update to Bootstrap Datepicker "format" in ht_datepicker_jquery.php.

Sources:
[https://eonasdan.github.io/bootstrap-datetimepicker/Options/#format](url)
[http://momentjs.com/docs/#/displaying/format/](url)

### CODE REVIEW

**Comment by BrockleyJohn** [comment]
I'd never even noticed this on the catalog side. Where is it used/useful?

**Comment by raiwa** [comment]
DOB in: create_account.php, account_edit.php

Date added in: advanced_search.php

 

De: John Ferguson [mailto:notifications@github.com] 
Enviado el: domingo, 23 de abril de 2017 10:15
Para: gburton/Responsive-osCommerce
CC: Rainer Schmied; Author
Asunto: Re: [gburton/Responsive-osCommerce] Datepicker update to Bootstrap Datepicker "format" (#548)

 

I'd never even noticed this on the catalog side. Where is it used/useful?

**Comment by gburton** [comment]
You are sure about this @raiwa 
We are not using jquery datepicker, we use eyecon.ro datepicker.

**Comment by raiwa** [comment]
@gburton please try yourself:
change the date format in the main language file to:
`define('JQUERY_DATEPICKER_FORMAT', 'dd/mm/yy');`
then the datepicker in create account will still produce the default format:
mm/dd/yy
if you apply my suggested changes it will produce the modified format:
dd/mm/yy

rgds
Rainer

**Pull request closed without merging**
