### PR TITLE
PHP 7 class constructors

### PR DESCRIPTION
**Pull request by Piernas**
Changed named methods to PHP 7 compatible class constructors. (except
payment methods)

### CODE REVIEW

**Comment by gburton** [comment]
Closed. 

Too many changes in 1 commit.  This is the reason I asked and advised to do just 1 small group, and then push it.

**Comment by Piernas** [comment]
Sorry I didn't read it. Just tested about 20 of them but it's the same copy-paste single line modification so it should work in all of them. Do you want me to test each of them one by one?

**Comment by gburton** [comment]
https://github.com/gburton/Responsive-osCommerce/issues/288#issuecomment-199838053

Select 1 "group" eg, all the ones in includes/classes/
**AND comment to let others know the group you are working on.**

Make the changes, **TEST FULLY**, then push.

And then wait for others to test your changes.  When it then gets into Core, repeat the process.

**Comment by Piernas** [comment]
fine, I'll choose one and post in the issues section.

**Pull request closed without merging**
