### PR TITLE
Update bm_best_sellers.php

### PR DESCRIPTION
**Pull request by jwisdom**
The Google structured data tool was showing an error for not having the position defined.  After getting that to work, it needed the url to fully work.  Tested and there are no errors.

### CODE REVIEW

**Comment by gburton** [comment]
Pls push to branch: Updates
TY

**Comment by jwisdom** [comment]
Can I do " push to branch: Updates" from the Git website?  I haven't done anythign with this in a while and I don't rember how.  I just used the web editing tool to add that.  Sorry, I'm a little lost.

**Comment by gburton** [comment]
TY John

**Comment by jwisdom** [comment]
YW Gary

 

John Wisdom

www.DriedFlowersRus.com <https://www.driedflowersrus.com/> 

Toll Free 888-527-5778

**Pull request merged**
