### PR TITLE
Update template_top.php

### PR DESCRIPTION
**Pull request by gburton**
Font Awesome -> 4.6.0

### CODE REVIEW

**Comment by skleiner** [comment]
Update shop to this, will keep an eye on things.

**Comment by gburton** [comment]
Thank You Steve @skleiner

**Comment by Kymation** [comment]
4.6.1 is already out. Running it on a test store; no problems so far.

**Comment by skleiner** [comment]
Running PHP Version:	5.5.34 (Zend: 2.5.0). So far so good with this update.

**Pull request merged**
