### PR TITLE
Product listing typo

### PR DESCRIPTION
**Pull request by crazy-colorado**
Found a missing " mark in product listing.

### CODE REVIEW

**Comment by BrockleyJohn** [comment]
That's not the only difference in this pull request

**Comment by crazy-colorado** [comment]
I found two other issues that I corrected with the same pull request.  With each fix I made comments.  I can recreate the pull; however, the changes are all within this current pull.

**Comment by gburton** [comment]
L166:  you have added itemscope, this is not needed per Schema example markup.
Please resubmit only the missing apostrophe, thanks!

**Comment by crazy-colorado** [comment]
I do agree that my initial research showed that the Schema does not state it is required; however, after some poking around (https://schema.org/docs/gs.html) itemscope and itemtype are used hand in hand.  W3c validation of a product listing page outputted many HTML errors.  Adding the itemscope was the solution.

**Comment by gburton** [comment]
Get rid of the extra markup please.  Resubmit only the typo, thanks.

**Pull request closed without merging**
