### PR TITLE
Minimum Length - First Name

### PR DESCRIPTION
**Pull request by gburton**
Checks that the minimum length set in admin has been adhered to.

### CODE REVIEW

**Comment by gburton** [comment]
Should this be added ?  Would need to do the same for a lot more "min length" things.  Or should we just rip out the minimum length settings entirely.

**Comment by skleiner** [comment]
Using just and initial instead of the full name has legitimate purposes.  Helping maintain a bit of anonymity for whatever reason.  For example a female may wish to just use an initial and not provide gender information for legitimate reasons.

**Comment by MOPS-DanCole** [comment]
HI Gary, I just saw this and realized that you could discuss these changes here.  I think I would keep it simple and not force minimum lengths.  Required and not required goes far enough from my point of view. 

Dan

**Comment by gburton** [comment]
It sounds like you both feel that this minlength should be ripped out ? @skleiner @MOPS-DanCole

**Comment by skleiner** [comment]
That's correct.  Just wondering, is there a max limit?

**Comment by MOPS-DanCole** [comment]
Yes I feel that way Gary...I don't see the need for a minimum length especially if we have control over whether a field is required or not.

**Comment by gburton** [comment]
OK, I'm going to rip out the minlength fields.

**Comment by gburton** [comment]
Said that, I do quite like the flexibility of:

minlength="' . (int)ENTRY_FIRST_NAME_MIN_LENGTH . '"

**Comment by skleiner** [comment]
If minlength="' . (int)ENTRY_FIRST_NAME_MIN_LENGTH . '" would allow the shopowner to set their on min length in a config type setting then that is the best route I'd think.

**Comment by gburton** [comment]
@skleiner - the configs are already in the DB (and in fact are used in post submit checking, eg:

https://github.com/gburton/Responsive-osCommerce/blob/master/create_account.php#L67-L71

What I think would be "nice" is to give an indication of that potential prior to submission, and that can be done by adding

minlength="' . (int)ENTRY_FIRST_NAME_MIN_LENGTH . '" 

to the (eg) first_name input box.

However, the html5 minlengh is not supported in mny browsers (yet), but it is accepted and coming in all browsers...

**Comment by gburton** [comment]
See http://caniuse.com/#search=minlength

**Comment by skleiner** [comment]
I'd forgotten about the min lengths in config, that's how long it's been since I've looked at them, and now I rethink my opinion.   If I'm setting min length of first name in config to be "1", then that probably addresses my situation.  And because some shop owner may want say..a min of 2 or 3 for their own good reason, perhaps the code should enforce that?  I can't think of an example to make that case though.   Sorry to be flipping around on this but new understanding  brings new point of view.  

but I believe I get the point now of (int)ENTRY_FIRST_NAME_MIN_LENGTH, and if that means the customer is going to see what is required of him/her, that's a good thing.

**Comment by MOPS-DanCole** [comment]
I'm not having any second thoughts Gary....if we can control whether input is required for a particular field I think that should be sufficient.  Requiring some input for a particular field would ensure that at least one character would need to be entered and would address Steve's situation.  I can't think of a reason for wanting to force a minimum number of characters except for perhaps something like a password where some special handling might be required.

**Pull request closed without merging**
