### PR TITLE
Deleting products content while previewing

### PR DESCRIPTION
**Pull request by oscwebshop-nl**
Products preview button creates the situation, that if you click on the back button, it erases a lot of the product settings.

Added back the original "read=only" part to make it read only again

### CODE REVIEW

**Comment by gburton** [comment]
read=only has not existing in osCommerce for a while...

**Comment by oscwebshop-nl** [comment]
Hi Gary,

That’s how it was done in my 2.2 version.
If you think there’s a better way of doing it, great I thought this was a quick win.

Domé

Van: gburton [mailto:notifications@github.com]
Verzonden: vrijdag 11 mei 2018 13:42
Aan: gburton/Responsive-osCommerce
CC: info.oscwebshop.nl; Author
Onderwerp: Re: [gburton/Responsive-osCommerce] Deleting products content while previewing (#671)


read=only has not existing in osCommerce for a while...

**Comment by gburton** [comment]
It's not in the category page in 2.3.4.1 (official osC)...

**Comment by gburton** [comment]
TY

**Pull request merged**
