### PR TITLE
Update jQuery to v2.2.2

### PR DESCRIPTION
**Pull request by gburton**

### CODE REVIEW

**Comment by skleiner** [comment]
Testing on live shop. Preliminary results with no observed issues. Site browsing, log in, test purchase, log off.
If there's a specific routine that uses the new jquery that needs tested please advise.

**Comment by gburton** [comment]
@skleiner thanks (as always!) for testing.  No particular testing procedure other than general use.  I've been using 2.2.2 on a few test shops for a week with no problems seen...

**Comment by Tsimi78** [comment]
Also quickly installed and tested on my local (XAMPP) test shop. Looks good thus far.
No conflicts or hiccups on both sides (catalog & admin area)

**Comment by Piernas** [comment]
Tested on live test shop. No issues found.

**Comment by gburton** [comment]
Thank you all

**Pull request merged**
